inputPlayers/inputPlayers.html
inputPlayers/inputPlayers.js

adding dbf file and scripting for the inputPlayers

---

prizeMoney/prizeMoney.html

added table to html, created js file

---

prizeMoney/prizeMoney.html

Created a table that should work

Updated Table

---

prizeMoney/prizeMoney.html

New Table with better functionalities

Redesigned Table

---

dashboard.css
index.html

Added links to the main homepage

---

dashboard.css
index.html

fixed link issues

---

index.html

added event and donate button

---

inputPlayers/inputPlayers.html
inputPlayers/inputPlayers.js

adds a new form for each player. I will
continue to work on getting the data to a JSON
object and send it to the server.

reworked adding new row for players, instead it

---

inputPlayers/inputPlayers.html
inputPlayers/inputPlayers.js

them in an array of JSON objects to be used to
check validity, expiration date,
and then send to server to be used in the
tournament.

Added function to take all the players and put

---

SearchPlayer/searchPlayer.html
index.html
inputPlayers/inputPlayers.html
inputPlayers/inputPlayers.js
prizeMoney/prizeMoney.html
scoreReport/scoreReport.html
server.js
tournament/tournament.html

consistent with all pages. Added functions
inputPlayers.js to handle the input of players.

Changed order of Search Player page to keep

---

SearchPlayer/searchPlayer.html
SearchPlayer/searchPlayer.js
inputPlayers/inputPlayers.html
inputPlayers/inputPlayers.js
playersController.js
server.js

players playing in the tournament.
As of right now, if a ID is searched and is
valid, it will be automatically added to the
players list. In the future, I will work on
seperating the search and add functonality.

Implemented backend file to keep a record of

---

SearchPlayer/searchPlayer.html
SearchPlayer/searchPlayer.js

check the expiration date and check if the
name is invalid. Also added a new function to
check if the player is already in the database.

added functionality to search player that will

---

SearchPlayer/searchPlayer.js

fixed function to check if player is already

---

dbfGenerator/dbfGenerator.html
index.html
server.js

Added Navigation for the DBFGenerator page

Fixed Navigation

---

SearchPlayer/searchPlayer.html
addSection/addSection.html
index.html
prizeMoney/prizeMoney.html
scoreReport/scoreReport.html
server.js
tournament/tournament.html

added addSection page to be updated

---

addSection/addSection.html
playersController.js
scoreReport/scoreReport.html
server.js

and saves the updated info to samplePlayers

adds Player Secitons and Score Reoprt Post request

---

playersController.js
scoreReport/scoreReport.html
server.js

adds scoreReportupdate function to

---

prizeMoney/prizeMoney.html

added function to calculate the highets scores and display to the console.

---

playersController.js
prizeMoney/prizeMoney.html

finished prize money

---

dbfController.js
dbfGenerator/dbfGenerator.html
dbfGenerator/dbfGenerator.js
server.js

Updated writeTD as well as the dbfGenerator html such that an event ID must be provided and then the results of the tournament will be (mostly) generated

Updated writeTD
